#!/bin/sh
# Added to verify Test coverage

# Using "mvn test" to run all unit tests and run plugins to assert
#   * code coverage threshold >= 85% (using surefire, enforcer plugins)
#   * Checkstyle has 0 errors (using maven-checkstyle-plugin)
mvn clean install test
RESULTS=$?
# Perform checks

if [ $RESULTS -ne 0 ]; then
  echo Error: Commit criteria not met with one or more of the following issues,
  echo 1. Failure(s) in unit tests
  echo 2. Failure to meet 80% code coverage
  echo 3. Failure to meet 0 Checkstyle errors
  exit 1
fi
# You shall commit
exit 0
